# vsetvli rd, rs1, vtype1
# rd = new vl, rs1 = AVL, vtypei = new vtype setting
#########################################################
vsetvli x0, x17,        # vlmul = 1, vsew = 8



# vsetivli rd, uimm, vtypei
# rd = new vl, uimm = AVL, vtypei = new vtype setting
########################################################



# vsetvl rd, rs1, rs2
# rd = new vl, rs1 = AVL, vtypei = new vtype value  